
name: develop

on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs: 
  build:

    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - run: pip3 install conan

      - run: brew install ninja libimobiledevice
        if: ${{ matrix.os == 'macos-latest'}}

      - run: sudo apt-get update && sudo apt-get install -y ninja-build libimobiledevice-dev
        if: ${{ matrix.os == 'ubuntu-latest'}}

      # - run: choco install ninja libimobiledevice
      #   if: ${{ matrix.os == 'windows-latest'}}

      - uses: lukka/run-cmake@v3
        with:
          cmakeAppendedArgs: '-GNinja'
          buildDirectory: ${{ env.buildDir }}
          configurationRegexFilter: '${{ matrix.configuration }}'
