
name: develop

on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:

    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2

      - if: ${{ matrix.os == 'macos-latest'}}
        run: brew install ninja libimobiledevice conan

      - if: ${{ matrix.os == 'ubuntu-latest'}}
        run: sudo apt-get update && sudo apt-get install -y ninja-build libimobiledevice-dev && pip3 install conan

      - if: ${{ matrix.os == 'windows-latest'}}
        run: |
          choco install ninja conan
          refreshenv

      - uses: lukka/run-cmake@v3
        with:
          cmakeBuildType: "Release"
          buildDirectory: ${{ env.buildDir }}
          configurationRegexFilter: '${{ matrix.configuration }}'
          buildWithCMakeArgs: '-- all package'
