
name: develop

on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs: 
  build:
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/run-cmake@v3
        with:
          cmakeAppendedArgs: '-GNinja'
          buildDirectory: ${{ env.buildDir }}
          # Or build multiple configurations out of a CMakeSettings.json file created with Visual Studio.
          # cmakeListsOrSettingsJson: CMakeSettingsJson
          # cmakeSettingsJsonPath: '${{ github.workspace }}/cmakesettings.json/CMakeSettings.json'
          configurationRegexFilter: '${{ matrix.configuration }}'
