
name: develop

on: [push]
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs: 

  linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libimobiledevice
  windows:
    runs-on: windows-latest
    steps:
      - run: choco install ninja libimobiledevice
  mac:
    runs-on: macos-latest
    steps:
      - run: brew install ninja libimobiledevice

  build:
    env:
      buildDir: '${{ github.workspace }}/build'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Install xmllint
        run: sudo apt-get install -y libimobiledevice
      - uses: actions/checkout@v2
      - run: pip3 install conan
      - uses: lukka/run-cmake@v3
        with:
          cmakeAppendedArgs: '-GNinja'
          buildDirectory: ${{ env.buildDir }}
          # Or build multiple configurations out of a CMakeSettings.json file created with Visual Studio.
          # cmakeListsOrSettingsJson: CMakeSettingsJson
          # cmakeSettingsJsonPath: '${{ github.workspace }}/cmakesettings.json/CMakeSettings.json'
          configurationRegexFilter: '${{ matrix.configuration }}'
